### ISSUE TITLE
How do I install these drivers on my device?

### ISSUE THREAD

**Issue by Xinmudotmoe** [gus33000/MSM8974-NT-ARM-Drivers#1]
I tried to install these drivers using DISM.exe, but I failed. WP10 does not seem to exist a file. How should I install these drivers?

My device version is 10.0.15254 (mobile).

> DISM does not support servicing a Windows Vista RTM or earlier operating system.
> If the operating system is supported check that SSShim.DLL is present.

**Comment by gus33000** [comment]
These drivers are not for Windows 10 Mobile but Windows Desktop (Client).
